//go:build windows

package main

import (
	_ "embed"

	"github.com/energye/systray"
)

// trayIcon is the .ico shown in the system tray (generated by wails from CC.png).
//
//go:embed build/windows/icon.ico
var trayIcon []byte

// startTray runs the system tray in its own goroutine (energye/systray supports
// this on Windows without owning the main thread, which Wails needs).
func (a *App) startTray() {
	go systray.Run(a.onTrayReady, func() {})
}

func (a *App) onTrayReady() {
	if len(trayIcon) > 0 {
		systray.SetIcon(trayIcon)
	}
	systray.SetTitle("ChromaCube Launcher")
	systray.SetTooltip("ChromaCube Launcher")

	mOpen := systray.AddMenuItem("Open", "Show the launcher window")
	systray.AddSeparator()
	mConnect := systray.AddMenuItem("Connect", "Connect to the network")
	mDisconnect := systray.AddMenuItem("Disconnect", "Disconnect from the network")
	systray.AddSeparator()
	mClose := systray.AddMenuItem("Close", "Quit the launcher")

	mOpen.Click(func() { a.showWindow() })
	mConnect.Click(func() { a.ConnectAll() })
	mDisconnect.Click(func() { a.DisconnectAll() })
	mClose.Click(func() { a.quitApp() })

	// Left-click the tray icon opens the window; right-click shows the menu.
	systray.SetOnClick(func(menu systray.IMenu) { a.showWindow() })
	systray.SetOnRClick(func(menu systray.IMenu) { _ = menu.ShowMenu() })
}
